# -*- coding: utf-8 -*-
"""Mihika_Rohatgi_10901012025_Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6CUkg67IRZJ7pLvNhocKCLJXiGsNKpF
"""

#Q1. Find sum of first 10 natural numbers
sum=0
for i in range(1,11):
  sum+=i
print("sum of first 10 natural numbers is:", sum)

#Q2. Find factorial of a number
x=int(input("Enter a number:"))
fact=1
for i in range(0,x):
  fact=fact*x
  x-=1
print("Factorial of given number is:", fact)

#Q3. Print Fibonacci Series
x=int(input("Enter number of terms:"))
a=0
b=1
print(a)
print(b)
for i in range(1,x-1):
  c=a+b
  print(c)
  a=b
  b=c

#Q4. Find largest among 3 numbers
x=int(input("Enter first number:"))
y=int(input("Enter second number:"))
z=int(input("Enter third number:"))
max=x
if y>max:
  max=y
if z>max:
  max=z
print("Largest number among given 3 is:", max)

#Q5. Create Student Result System
#input student details
name=input("Enter student name:")
enrol=int(input("Enter enrollment number:"))
branch=input("Enter branch:")
#input marks
DSA=int(input("Enter marks in DSA:"))
IDS=int(input("Enter marks in IDS:"))
PS=int(input("Enter marks in PS:"))
SSPD=int(input("Enter marks in SSPD:"))
#calc perecentage
tot=DSA+IDS+PS+SSPD
percent=(tot/400) * 100
#display grade
if percent >= 93:
    grade = "A+"
elif percent >= 85:
    grade = "A"
elif percent >= 77:
    grade = "B+"
elif percent >= 69:
    grade = "B"
elif percent >= 61:
    grade = "C+"
elif percent >= 53:
    grade = "C"
elif percent >= 45:
    grade = "D"
else:
    grade = "F"
#display report
print("----------- Student Report -----------")
print("Student Name:", name)
print("Enrollment number:", enrol)
print("Branch:", branch)
print("Marks in DSA:", DSA)
print("Marks in IDS:", IDS)
print("Marks in PS:", PS)
print("Marks in SSPD:", SSPD)
print("--------------------------------------------")
print("Total Marks:", tot)
print("Percentage:", percent)
print("Grade:", grade)
print("--------------------------------------------")